image: dremio/dremio-oss
# Check out Dremio documentation for memory and cpu requirements for
# the coordinators and the executors.
# The value of memory should be in MB. CPU is in no of cores.
coordinator:
  memory: 1280
  cpu: 1
  count: 0
  # This value should NOT be set to more than 1.
  master_count: 1
  web:
    port: 9047
  client:
    port: 31010
  volumeSize: 10Gi
executor:
  memory: 1024
  cpu: 1
  count: 1
  volumeSize: 10Gi
# If your Kubernetes cluster does not support LoadBalancer,
# comment out the line below for the helm chart to succeed or add
# the correct serviceType for your cluster.
serviceType: LoadBalancer

# If the loadBalancer supports sessionAffinity and
# you have one or more coordinators, enable it
#sessionAffinity: ClientIP

# To use custom storage class, uncomment and provide the value here.
# Otherwise the default storage class configured for your K8S cluster is used.
#storageClass: managed-premium

# For private and protected docker image repository, you should store
# the credentials in a kubernetes secret and provide the secret name here.
# For more information, see https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
#imagePullSecrets=secretname
